// Prose that goes out under Abay's name. Edit freely — the point is that it
// sounds like him, not like a template.

export const heroSummary =
  "I work on quantum impurities in one-dimensional systems, mostly Kondo problems, " +
  "using the Bethe ansatz and its finite-temperature extension to get exact results " +
  "where perturbation theory runs out. Lately I've been working on boundaries: what " +
  "happens to the impurity entropy when the boundary binds a localized state of its " +
  "own, and what Kondo screening looks like when the host is a superconductor.";

export const researchOverview = [
  "I study how a single impurity, or a boundary, changes the thermodynamics of an " +
    "integrable one-dimensional system. The tools are exact ones — the Bethe ansatz and " +
    "the thermodynamic Bethe ansatz (TBA), which give the free energy at finite " +
    "temperature without approximation. Most of the problems I have worked on are Kondo " +
    "problems in hosts where the screening competes with something else: superconducting " +
    "pairing, a PT-symmetric non-Hermitian coupling, or a small number of conduction " +
    "channels.",
  "The recent work develops a TBA framework for open boundaries that support boundary " +
    "bound modes — localized states generated by the boundary interaction itself. We used " +
    "it to compute the impurity residual entropy and its RG flow in a superconducting " +
    "wire, in the multichannel version of that problem, and in the spin-S Heisenberg " +
    "chain. A separate line of work applies Bethe ansatz methods to Kondo physics in " +
    "strongly interacting and PT-symmetric environments: heavy-quark impurities at the " +
    "edge of a color superconductor, and entropy-flow anomalies in multichannel " +
    "PT-symmetric Kondo models.",
];

export const aboutBio = [
  "I grew up in Kazakhstan and studied at MIPT in Moscow, where I did my bachelor's and " +
    "master's with Vladimir Belavin on integrable structures in conformal field theory, " +
    "with a research stint at the Landau Institute. I came to Rutgers in 2021 for a PhD " +
    "with Natan Andrei.",
  "I teach a lot, and not only because it comes with the job. I have TA'd across " +
    "Rutgers' introductory and intermediate physics sequences, run a summer quantum " +
    "computation course over Zoom for high-school students in Kazakhstan, coached " +
    "olympiad students, and tutored privately from high school up through graduate level. " +
    "Outside all of that I play soccer and train judo.",
];
